language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - python setup.py -q install
  - "python -c \"import nltk; nltk.download(['stopwords', 'punkt'])\""
script: nosetests
